const products = [
    {
        id: 'P00001',
        counter: 1,
        name: 'Eye active capsules', 
        images: [
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
        ],
        price: 157.58,
        description: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        consumption: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        itemNumber: `Art. Nr.: 010018019 | GTIN: 4004148346538 | PZN: 17525988`,
    },
    {
        id: 'P00002',
        counter: 2,
        name: 'Saluvision, Eye protection capsules',
        images: [
          { url: 'http://gc-pharma.herokuapp.com/public/product2.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product2.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product2.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product2.png' },
        ],
        price: 109.0,
        description: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        consumption: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        itemNumber: `Art. Nr.: 010018019 | GTIN: 4004148346538 | PZN: 17525988`,
    },
    {    
        id: 'P00003',
        counter: 3,
        name: 'Abacavir',
        images: [
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
        ],
        price: 99.9,
        description: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        consumption: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        itemNumber: `Art. Nr.: 010018019 | GTIN: 4004148346538 | PZN: 17525988`,
    },
    {
        id: 'P00004',
        counter: 4,
        name: 'C 300 depot with zinc',
        images: [
          { url: 'http://gc-pharma.herokuapp.com/public/product3.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product3.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product3.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product3.png' },
        ],
        price: 172.6,
        description: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        consumption: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        itemNumber: `Art. Nr.: 010018019 | GTIN: 4004148346538 | PZN: 17525988`,
    },
    {
        id: 'P00005',
        counter: 5,
        name: 'Amifostine',
        images: [
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
          { url: 'http://gc-pharma.herokuapp.com/public/product1.png' },
        ],
        price: 12.6,
        description: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        consumption: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`,
        itemNumber: `Art. Nr.: 010018019 | GTIN: 4004148346538 | PZN: 17525988`,
    },
];

export default products;